# Generated by Django 3.0.6 on 2020-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0002_auto_20200524_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprogmodel',
            name='Textao',
            field=models.TextField(max_length=2000),
        ),
    ]
