# Generated by Django 3.0.6 on 2020-06-13 17:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0003_auto_20200602_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porcentagem', models.IntegerField(max_length=3)),
                ('Corretas', models.IntegerField(max_length=3)),
                ('Incorretas', models.IntegerField(max_length=3)),
                ('Campo4', models.IntegerField(max_length=3)),
                ('Campo5', models.IntegerField(max_length=3)),
            ],
            managers=[
                ('objetos2', django.db.models.manager.Manager()),
            ],
        ),
    ]
