# Generated by Django 3.0.6 on 2020-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0004_calculosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Marcador1',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Marcador2',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Marcador3',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Marcador4',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Marcador5',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='DuvidaComent',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='OndeFigura1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='Textao',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='Topico',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
