# Generated by Django 3.0.6 on 2020-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0005_auto_20200613_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculosmodel',
            name='Campo4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Campo5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Corretas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Incorretas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Porcentagem',
            field=models.IntegerField(),
        ),
    ]
