# Generated by Django 3.0.6 on 2020-06-20 18:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0006_auto_20200613_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordem', models.IntegerField()),
                ('NTopico', models.IntegerField()),
                ('Acertou', models.IntegerField(default=0)),
            ],
            managers=[
                ('objeto_sessao', django.db.models.manager.Manager()),
            ],
        ),
    ]
