# Generated by Django 3.0.6 on 2020-06-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0007_sessaomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculosmodel',
            old_name='Campo4',
            new_name='Ordem',
        ),
        migrations.RemoveField(
            model_name='calculosmodel',
            name='Campo5',
        ),
    ]
