# Generated by Django 3.0.6 on 2020-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0008_auto_20200620_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Acertou',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Jafoi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='OndeFigura2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Ordem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='participante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
