# Generated by Django 3.0.6 on 2020-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0009_auto_20200626_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Ativada',
            field=models.IntegerField(default=1),
        ),
    ]
