# Generated by Django 3.0.6 on 2020-06-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0011_auto_20200627_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprogmodel',
            name='Acertou',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='Ativada',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='Jafoi',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='eprogmodel',
            name='Ordem',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
