# Generated by Django 3.0.6 on 2020-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0012_auto_20200627_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='SuaResposta',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
