# Generated by Django 3.0.6 on 2020-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0013_eprogmodel_suaresposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Corretas',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='Porcentagem',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
    ]
