# Generated by Django 3.0.6 on 2020-06-30 22:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0014_auto_20200628_1634'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessaomodel',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='sessaomodel',
            name='NTopico',
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Dia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Horario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Modulo',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Participante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='SeDuvidaComent',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Sessao',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Tentativa',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Topico',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sessaomodel',
            name='Acertou',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='sessaomodel',
            name='Ordem',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='sessaomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
