# Generated by Django 3.0.6 on 2020-06-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0015_auto_20200630_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaomodel',
            name='SeDuvidaComent',
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='DuvidaComent',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
