# Generated by Django 3.0.6 on 2020-07-02 17:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0016_auto_20200630_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Participante', models.CharField(blank=True, default='', max_length=200)),
                ('Banco', models.TextField(blank=True, default='', max_length=500)),
                ('NomeCompleto', models.CharField(blank=True, default='', max_length=200)),
                ('Idade', models.TextField(blank=True, default='', max_length=3)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
