# Generated by Django 3.0.6 on 2020-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0017_procedimentomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso',
            field=models.TextField(blank=True, default='', max_length=10),
        ),
    ]
