# Generated by Django 3.0.6 on 2020-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0018_procedimentomodel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Botao_avalia',
            field=models.TextField(blank=True, default='', max_length=3),
        ),
    ]
