# Generated by Django 3.0.6 on 2020-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0019_procedimentomodel_botao_avalia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Botao_avalia',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
