# Generated by Django 3.0.6 on 2020-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0020_auto_20200707_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='SessaoAtual',
            field=models.TextField(blank=True, default='1', max_length=3),
        ),
    ]
