# Generated by Django 3.0.6 on 2020-10-04 20:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0021_procedimentomodel_sessaoatual'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='calculosmodel',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
