# Generated by Django 3.2.4 on 2021-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0022_auto_20201004_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eprogmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
