# Generated by Django 3.2.7 on 2022-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0023_auto_20210730_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Modulo',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
    ]
