# Generated by Django 3.2.7 on 2022-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0024_eprogmodel_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='Numero',
            field=models.CharField(blank=True, default=' ', max_length=3),
        ),
    ]
