# Generated by Django 3.2.7 on 2022-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0025_eprogmodel_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculosmodel',
            name='Modulo',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='calculosmodel',
            name='Numero',
            field=models.CharField(blank=True, default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='QualModulo',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='sessaomodel',
            name='Numero',
            field=models.CharField(blank=True, default=' ', max_length=3),
        ),
    ]
