# Generated by Django 3.2.7 on 2022-06-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0026_auto_20220615_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimentomodel',
            old_name='QualModulo',
            new_name='Modulo',
        ),
    ]
