# Generated by Django 3.2.7 on 2022-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0027_rename_qualmodulo_procedimentomodel_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprogmodel',
            name='SobreModulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
