# Generated by Django 3.2.7 on 2022-06-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0028_eprogmodel_sobremodulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimentomodel',
            old_name='Modulo',
            new_name='ModuloAtual',
        ),
        migrations.RemoveField(
            model_name='eprogmodel',
            name='SobreModulo',
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='ModuloFinal',
            field=models.TextField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo10',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo11',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo12',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo13',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo14',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo15',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo16',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo17',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo18',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo19',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo20',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo5',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo6',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo7',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo8',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='SobreModulo9',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
