# Generated by Django 3.2.7 on 2022-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0029_auto_20220615_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculosmodel',
            name='TotalModulo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Corretas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculosmodel',
            name='Porcentagem',
            field=models.IntegerField(default=0),
        ),
    ]
