# Generated by Django 3.2.7 on 2022-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0031_procedimentomodel_modulocontinuar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='ModuloContinuar',
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='ModuloRetreino',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
    ]
