# Generated by Django 3.2.7 on 2022-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0032_auto_20220618_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='ModuloRetreino',
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='ModuloAntigo',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
    ]
