# Generated by Django 3.2.7 on 2022-06-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0035_pretestemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestemodel',
            name='Escolheu',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
