# Generated by Django 3.2.7 on 2022-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0036_pretestemodel_escolheu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Escolheu',
            field=models.CharField(choices=[('a', 'Alternativa_A'), ('b', 'Alternativa_B'), ('c', 'Alternativa_C')], max_length=10),
        ),
    ]
