# Generated by Django 3.2.7 on 2022-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0037_auto_20220622_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestemodel',
            name='Escolheu',
            field=models.CharField(blank=True, choices=[('a', 'Alternativa_A'), ('b', 'Alternativa_B'), ('c', 'Alternativa_C'), ('d', 'Alternativa_D'), ('e', 'Alternativa_E')], max_length=10),
        ),
    ]
