# Generated by Django 3.2.7 on 2022-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0039_alter_pretestemodel_escolheu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestemodel',
            name='Escolheu',
            field=models.CharField(blank=True, choices=[(models.CharField(blank=True, default='', max_length=200), 'Available to borrow'), (models.CharField(blank=True, default='', max_length=200), 'Borrowed by someone'), (models.CharField(blank=True, default='', max_length=200), 'Archived - not available anymore'), (models.CharField(blank=True, default='', max_length=200), 'aqui a D'), (models.CharField(blank=True, default='', max_length=200), 'aqui a E')], max_length=10),
        ),
    ]
