# Generated by Django 3.2.7 on 2022-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0043_alter_pretestemodel_escolheu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestemodel',
            name='Escolheu',
            field=models.CharField(blank=True, choices=[('a)', 'a)'), ('b)', 'b)'), ('c)', 'c)'), ('d)', 'd)'), ('e)', 'e)')], max_length=10, unique=True),
        ),
    ]
