# Generated by Django 3.2.7 on 2022-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0046_auto_20220623_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteFim_20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
