# Generated by Django 3.2.7 on 2022-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0047_auto_20220626_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTesteUltimoModulo_20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
