# Generated by Django 3.2.7 on 2022-06-28 03:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0048_auto_20220627_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostesteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ordem', models.CharField(blank=True, default='', max_length=3)),
                ('Modulo', models.CharField(blank=True, default='1', max_length=3)),
                ('Acertou', models.CharField(blank=True, default='0', max_length=3)),
                ('Jafoi', models.CharField(blank=True, default='0', max_length=3)),
                ('Questao', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_A', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_B', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_C', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_D', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_E', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_X', models.CharField(blank=True, default='', max_length=200)),
                ('Alternativa_A_escolhida', models.CharField(blank=True, default='0', max_length=3)),
                ('Alternativa_B_escolhida', models.CharField(blank=True, default='0', max_length=3)),
                ('Alternativa_C_escolhida', models.CharField(blank=True, default='0', max_length=3)),
                ('Alternativa_D_escolhida', models.CharField(blank=True, default='0', max_length=3)),
                ('Alternativa_E_escolhida', models.CharField(blank=True, default='0', max_length=3)),
                ('Escolheu', models.CharField(blank=True, default='', max_length=3)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
