# Generated by Django 3.2.7 on 2022-06-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0049_postestemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='FimEstudo',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
