# Generated by Django 3.2.7 on 2022-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0050_procedimentomodel_fimestudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='FimUltimoModulo',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
