# Generated by Django 3.2.7 on 2022-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0051_procedimentomodel_fimultimomodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postestemodel',
            name='Participante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pretestemodel',
            name='Participante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
