# Generated by Django 3.2.7 on 2022-07-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0052_auto_20220702_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_01',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_02',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_03',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_04',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_05',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_06',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_07',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_08',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_09',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_10',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_11',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_12',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_13',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_14',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_15',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_16',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_17',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_18',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_19',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTeste_Estado_20',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_01',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_02',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_03',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_04',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_05',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_06',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_07',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_08',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_09',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_10',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_11',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_12',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_13',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_14',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_15',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_16',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_17',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_18',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_19',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PreTeste_Estado_20',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_01',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_02',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_03',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_04',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_05',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_06',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_07',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_08',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_09',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_10',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_11',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_12',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_13',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_14',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_15',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_16',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_17',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_18',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_19',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Treino_Estado_20',
            field=models.TextField(blank=True, default='n', max_length=3),
        ),
    ]
