# Generated by Django 3.2.7 on 2022-07-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0054_auto_20220715_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='procedimentomodel',
            name='Etapa20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
