# Generated by Django 3.2.7 on 2022-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0055_auto_20220715_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa_acesso20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
