# Generated by Django 3.2.7 on 2022-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0057_auto_20220715_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso01_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso01_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso01_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso02_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso02_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso02_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso03_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso03_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso03_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso04_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso04_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso04_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso05_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso05_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso05_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso06_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso06_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso06_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso07_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso07_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso07_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso08_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso08_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso08_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso09_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso09_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso09_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso10_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso10_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso10_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso11_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso11_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso11_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso12_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso12_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso12_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso13_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso13_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso13_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso14_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso14_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso14_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso15_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso15_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso15_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso16_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso16_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso16_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso17_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso17_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso17_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso18_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso18_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso18_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso19_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso19_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso19_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso20_posteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso20_preteste',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Acesso20_treino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='Etapa20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
