# Generated by Django 3.2.7 on 2022-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0059_auto_20220716_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTestePrimeiroModulo_20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_01',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_02',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_03',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_04',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_05',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_06',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_07',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_08',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_09',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_10',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_11',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_12',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_13',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_14',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_15',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_16',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_17',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_18',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_19',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='procedimentomodel',
            name='PosTesteUltimoModulo_20',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
