# Generated by Django 3.2.7 on 2022-07-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0060_auto_20220716_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='AgoraTreino',
            field=models.TextField(blank=True, default='0', max_length=3),
        ),
    ]
