# Generated by Django 3.2.7 on 2022-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0062_auto_20220717_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='EtapaAtual',
            field=models.CharField(blank=True, default='pré-teste', max_length=30),
        ),
    ]
