# Generated by Django 3.2.7 on 2022-07-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0064_auto_20220721_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_A',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_B',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_C',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_D',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_E',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Alternativa_X',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='pretestemodel',
            name='Questao',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
