# Generated by Django 3.2.7 on 2022-07-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0065_auto_20220721_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Condicao',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
