# Generated by Django 3.2.7 on 2022-07-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0067_auto_20220725_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Senha_Experimentador',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
