# Generated by Django 3.2.7 on 2022-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0068_procedimentomodel_senha_experimentador'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentomodel',
            name='Senha_Salva',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
