# Generated by Django 3.2.7 on 2022-07-27 17:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0069_procedimentomodel_senha_salva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ordem', models.IntegerField()),
                ('NoModulo', models.CharField(blank=True, default='', max_length=3)),
                ('Descricao', models.CharField(blank=True, default='', max_length=200)),
                ('Treino_Primeiro', models.IntegerField()),
                ('Treino_Ultimo', models.IntegerField()),
                ('PreTeste_Primeiro', models.IntegerField()),
                ('PreTeste_Ultimo', models.IntegerField()),
                ('TemPosTeste', models.IntegerField()),
                ('PosTeste_Primeiro', models.IntegerField()),
                ('PosTeste_Ultimo', models.IntegerField()),
                ('Treino_Acesso', models.CharField(blank=True, default='1', max_length=3)),
                ('PreTeste_Acesso', models.CharField(blank=True, default='1', max_length=3)),
                ('PosTeste_Acesso', models.CharField(blank=True, default='1', max_length=3)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
