# Generated by Django 3.2.7 on 2022-07-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0074_remove_modulosmodel_modulo_etapaatual'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulosmodel',
            name='Modulo_EtapaAtual',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
    ]
