# Generated by Django 3.2.7 on 2022-07-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0075_modulosmodel_modulo_etapaatual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo1',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo10',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo11',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo12',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo13',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo14',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo15',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo16',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo17',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo18',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo19',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo2',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo20',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo3',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo4',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo5',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo6',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo7',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo8',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='SobreModulo9',
        ),
    ]
