# Generated by Django 3.2.7 on 2022-07-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0076_auto_20220729_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa01',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa02',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa03',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa04',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa05',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa06',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa07',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa08',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa09',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa10',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa11',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa12',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa13',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa14',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa15',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa16',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa17',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa18',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa19',
        ),
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='Etapa20',
        ),
    ]
