# Generated by Django 3.2.7 on 2022-07-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EprogApp', '0078_auto_20220729_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentomodel',
            name='PreTestePrimeiroModulo_01',
        ),
    ]
